kind: pipeline
name: default

steps:
- name: build
  image: python
  commands:
  - apt-get update && apt-get install -y -q pypy libgc-dev
  - pip install sphinx sphinx_rtd_theme
  - wget https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.1.0-src.tar.bz2
  - tar jxf pypy2.7-v7.1.0-src.tar.bz2
  - export RPY=$(pwd)/pypy2.7-v7.1.0-src/rpython/bin/rpython
  - make -C code
  - make -C code/benchmarks
  - make html

---

kind: pipeline
name: deploy

steps:
- name: build
  image: python
  commands:
  - apt-get update && apt-get install -y -q pypy libgc-dev
  - pip install sphinx sphinx_rtd_theme
  - wget https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.1.0-src.tar.bz2
  - tar jxf pypy2.7-v7.1.0-src.tar.bz2
  - export RPY=$(pwd)/pypy2.7-v7.1.0-src/rpython/bin/rpython
  - make -C code
  - make -C code/benchmarks
- name: deploy
  image: python
  commands:
  - apt-get update && apt-get install -y -q pypy libgc-dev texlive-full latexmk
  - pip install sphinx sphinx_rtd_theme
  - make html
  - make latexpdf
  - mkdir -p ~/.ssh && echo $DOC_KEY | base64 -d > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  - cd _build/html && tar czf doc.tar.gz * && ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $DOC_USERNAME@$DOC_HOSTNAME "cd www/mesapy.org/rpython-by-example && rm -rf * && tar -xz" < doc.tar.gz
  - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no /drone/src/_build/latex/RPythonByExample.pdf $DOC_USERNAME@$DOC_HOSTNAME:~/www/mesapy.org/rpython-by-example/
  environment:
    DOC_KEY:
      from_secret: DOC_KEY
    DOC_USERNAME:
      from_secret: DOC_USERNAME
    DOC_HOSTNAME:
      from_secret: DOC_HOSTNAME

trigger:
  branch:
    - master
  event:
    - push
